import json
import os
import sys
import shutil
import unittest
from unittest.mock import patch


# Allow direct script execution: python backend/agent/test_summary_index_llm.py
repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)

from backend.agent.tools.retrieval import index_builder


class SummaryIndexLLMTests(unittest.TestCase):
    def _write_file(self, root: str, rel_path: str, content: str) -> None:
        full_path = os.path.join(root, rel_path)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(content)

    def test_missing_summary_triggers_llm_enrichment(self) -> None:
        repo = os.path.abspath(os.path.join(repo_root, "testcode"))
        index_root = os.path.join(repo, "summary")
        if os.path.exists(index_root):
            shutil.rmtree(index_root)

        def _fake_chat(prompt: str, system_prompt: str = "") -> str:
            payload = {
                "purpose": "calculator module",
                "main_symbols": ["compute"],
                "exports": ["compute"],
                "keywords": ["calculator", "math"],
                "depends_on": ["core/operations.py"],
                "notes": ["generated by fake llm"],
            }
            return json.dumps(payload, ensure_ascii=False)

        with patch("backend.doubao_llm.chat_with_doubao", side_effect=_fake_chat):
            manifest = index_builder.ensure_summary_index(
                repo_path=repo,
                query_points=["calculator", "math compute"],
                repo_skeleton="core/calculator.py -> core/operations.py",
            )

        self.assertEqual(manifest.get("summary_mode"), "llm_enriched")
        self.assertIn("core/calculator.py", manifest.get("files", {}))
        self.assertEqual(
            manifest["files"]["core/calculator.py"].get("summary_mode"),
            "llm",
        )

        manifest_path = os.path.join(repo, "summary", "manifest.json")
        self.assertTrue(os.path.exists(manifest_path))


if __name__ == "__main__":
    unittest.main()
